---
abstract: 'pixel-exact driver for EVOLIS Dualys two-side card printer in perl'
author:
  - 'Dobrica Pavlinusic <dpavlin@rot13.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Install::Repository: 0
  Pod::Readme: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Printer-EVOLIS
no_index:
  directory:
    - inc
    - t
    - test
requires:
  Data::Dump: 0
  Term::ReadLine: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dpavlin/Printer-EVOLIS.git
version: 0.01
